# Generated by Django 4.2.27 on 2026-02-02 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
