# Generated by Django 4.2.27 on 2026-02-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, help_text='e.g. Roman, Medieval, Victorian', max_length=100)),
                ('is_listed', models.BooleanField(default=False, help_text='Is this a listed/protected site?')),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('guided_tours_available', models.BooleanField(default=False)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heritage_features', to='places.place')),
            ],
        ),
    ]
