# Generated by Django 4.2.27 on 2026-02-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_heritagefeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(help_text='e.g. Italian, Pub food, Vegan', max_length=100)),
                ('price_range', models.PositiveSmallIntegerField(choices=[(1, '£'), (2, '££'), (3, '£££')], default=2)),
                ('vegetarian_options', models.BooleanField(default=False)),
                ('vegan_options', models.BooleanField(default=False)),
                ('takeaway_available', models.BooleanField(default=False)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_features', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='BeachFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_friendly', models.BooleanField(default=False)),
                ('lifeguard_present', models.BooleanField(default=False)),
                ('water_quality', models.CharField(blank=True, help_text='e.g. Excellent, Good, Poor', max_length=50)),
                ('facilities_available', models.BooleanField(default=False, help_text='Toilets, parking, cafés nearby')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beach_features', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='e.g. Hiking, Climbing, Escape Room', max_length=100)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_required', models.BooleanField(default=False)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_features', to='places.place')),
            ],
        ),
    ]
