# Generated by Django 4.2.27 on 2026-02-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0006_foodfeatures_beachfeatures_activityfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('activity_type', models.CharField(help_text='e.g. Hiking, Climbing, Escape Room', max_length=100)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='BeachPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('dog_friendly', models.BooleanField(default=False)),
                ('lifeguard_present', models.BooleanField(default=False)),
                ('water_quality', models.CharField(blank=True, help_text='e.g. Excellent, Good, Poor', max_length=50)),
                ('facilities_available', models.BooleanField(default=False, help_text='Toilets, parking, cafes nearby')),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('cuisine', models.CharField(help_text='e.g. Italian, Pub food, Vegan', max_length=100)),
                ('price_range', models.PositiveSmallIntegerField(choices=[(1, 'GBP'), (2, 'GBPGBP'), (3, 'GBPGBPGBP')], default=2)),
                ('vegetarian_options', models.BooleanField(default=False)),
                ('vegan_options', models.BooleanField(default=False)),
                ('takeaway_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='HeritagePlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('period', models.CharField(blank=True, help_text='e.g. Roman, Medieval, Victorian', max_length=100)),
                ('is_listed', models.BooleanField(default=False)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('guided_tours_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('places.place',),
        ),
        migrations.RemoveField(
            model_name='beachfeatures',
            name='place',
        ),
        migrations.RemoveField(
            model_name='foodfeatures',
            name='place',
        ),
        migrations.RemoveField(
            model_name='heritagefeatures',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='ActivityFeatures',
        ),
        migrations.DeleteModel(
            name='BeachFeatures',
        ),
        migrations.DeleteModel(
            name='FoodFeatures',
        ),
        migrations.DeleteModel(
            name='HeritageFeatures',
        ),
    ]
