# Generated by Django 4.2.27 on 2026-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0011_placelike_replace_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodplace",
            name="price_range",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "\u00A3"),
                    (2, "\u00A3\u00A3"),
                    (3, "\u00A3\u00A3\u00A3"),
                ],
                default=2,
            ),
        ),
    ]
