# Generated by Django 4.2.27 on 2026-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_foodplace_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='accessibility_info',
            field=models.TextField(blank=True, help_text='Wheelchair access, step-free notes, toilets, etc.'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='e.g. Early morning, sunset, summer.', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='child_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='estimated_visit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='parking_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='place',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='town_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='transport_info',
            field=models.TextField(blank=True, help_text='Public transport tips and nearest stops.'),
        ),
        migrations.AddField(
            model_name='place',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
