# Generated by Django 4.2.27 on 2026-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_place_archived_at_place_archived_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_approved', 'is_archived', 'category'], name='place_pub_arch_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_approved', 'is_archived', 'created_at'], name='place_pub_arch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['moderation_status', 'is_archived'], name='place_mod_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['town_city'], name='place_town_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['postcode'], name='place_postcode_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='place_name_idx'),
        ),
        migrations.AddIndex(
            model_name='placelike',
            index=models.Index(fields=['place', 'created_at'], name='placelike_place_created_idx'),
        ),
        migrations.AddIndex(
            model_name='placelike',
            index=models.Index(fields=['user', 'created_at'], name='placelike_user_created_idx'),
        ),
    ]
