# Generated by Django 4.2.27 on 2026-01-30 17:40

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_guest_name_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[reviews.validators.validate_review_language]),
        ),
    ]
