# Generated by Django 4.2.27 on 2026-02-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_review_moderation_penalty_applied_reviewreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('place_archived', 'Place Archived'), ('place_restored', 'Place Restored'), ('review_upheld', 'Review Report Upheld'), ('review_dismissed', 'Review Report Dismissed'), ('review_archived', 'Review Archived'), ('review_restored', 'Review Restored')], max_length=40)),
                ('object_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_user_per_place',
        ),
        migrations.AddField(
            model_name='review',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('place', 'user'), name='one_review_per_user_per_place'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
