# Generated by Django 4.2.27 on 2026-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_moderationlog_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['action', 'created_at'], name='modlog_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['content_type', 'object_id'], name='modlog_target_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['actor', 'created_at'], name='modlog_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', 'is_approved', 'is_archived', 'created_at'], name='review_place_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reported', 'is_archived', 'created_at'], name='review_report_arch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'is_archived', 'created_at'], name='review_user_arch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='review_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='revrep_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review', 'status'], name='reviewreport_review_status_idx'),
        ),
    ]
